# Generated by Django 4.0.4 on 2022-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atencionprofesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_profesional', models.CharField(max_length=50)),
                ('Motivo_de_atencion', models.CharField(max_length=200)),
                ('Proxima_visita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Nombre_tutorx', models.CharField(max_length=50)),
                ('Especie', models.CharField(max_length=50)),
                ('Raza', models.CharField(max_length=50)),
                ('Vacunas', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Ocupacion', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('nombre_mascota', models.CharField(max_length=50)),
            ],
        ),
    ]
